# Generated by Django 3.2.3 on 2021-05-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='color',
            name='rgb',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
